# Generated by Django 4.1.3 on 2022-11-05 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('vehicles', 'vehicles'), ('jewelry', 'jewelry'), ('watch', 'watch'), ('Electronics', 'Electronics'), ('Sports', 'sports'), ('Real Estate', 'Real Estate')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
