# Generated by Django 4.1.3 on 2022-11-06 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='addhar',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
